function sweep = run_step01_coast_observability_maneuver_ablation(makePlots)
%RUN_STEP01_COAST_OBSERVABILITY_MANEUVER_ABLATION Baseline angles-only EKF.
%
% This is the known-dynamics counterpart of the Step 09-J.6 N0-N3 coast
% experiment.  It deliberately removes the DNN state, parameter process
% noise, residual approximation error, and GS composition.  Consequently,
% differences between the four cases isolate the geometric information
% generated by the watcher maneuver.
%
%   E0 matched-velocity coast     no maneuver
%   E1 LOS-parallel               acceleration parallel to initial LOS
%   E2 LOS-transverse             same transverse sign for all watchers
%   E3 alternating transverse     alternating transverse signs
%
% Every available 0.01-deg bearing is used in a physical-state EKF update.
% The target truth and the EKF both use the same double-integrator model.
%
% Usage:
%   sweep01 = run_step01_coast_observability_maneuver_ablation(true);

% Important outputs:
%   sweep.summary             case-level metrics
%   sweep.watcherRangeSummary watcher-specific range metrics
%   sweep.results             complete simulation results
%   sweep.configs             exact configurations
%   sweep.figures             generated figure handles


    if nargin < 1
        makePlots = true;
    end

    addpath(genpath(pwd));
    seed = 101;
    cfgBase = config_step01_physical_EKF();

    cfgBase.T = 200.0;
    cfgBase.dt = 0.1;
    cfgBase.time = 0:cfgBase.dt:cfgBase.T;
    cfgBase.N = numel(cfgBase.time);

    cfgBase.scenario.watcherModel = "matched_velocity_coast";
    cfgBase.watchers.motionMode = "prescribed";
    cfgBase.watchers.coastVelocity = cfgBase.target.v0;
    cfgBase.control.translationMode = "none";

    cfgBase.meas.type = "bearing";
    cfgBase.meas.sigmaBearing = deg2rad(0.01);
    cfgBase.meas.R = cfgBase.meas.sigmaBearing^2;
    cfgBase.meas.availabilityMode = "always";
    cfgBase.fov.enabled = false;
    cfgBase.fov.guardUnimplementedMode = true;

    % Exact known-dynamics test: neither the truth nor the baseline EKF has
    % an unmodelled acceleration.  q_acc=0 avoids replacing the removed DNN
    % uncertainty by artificial physical process noise.
    cfgBase.truth.useResidual = false;
    cfgBase.ekf.q_acc = 0;

    cfgBase.control.obs.enabled = false;
    cfgBase.control.obs.mode = "none";
    cfgBase.control.obs.startTime = 40.0;
    cfgBase.control.obs.burnDuration = 50.0;
    cfgBase.control.obs.acceleration = 5e-4;

    caseNames = [
        "E0 baseline coast"
        "E1 LOS-parallel"
        "E2 LOS-transverse"
        "E3 alternating transverse"];
    maneuverModes = ["none"; "parallel"; "transverse"; ...
        "transverse_alternating"];
    nCases = numel(caseNames);

    results = cell(nCases,1);
    configs = cell(nCases,1);
    status = repmat("not run",nCases,1);

    fprintf("Step 01 baseline EKF coast observability-maneuver ablation\n");
    fprintf("known dynamics; no DNN and no target residual\n");
    fprintf("sigma_b=%.4f deg, T=%.1f s, dt=%.4g s, q_acc=%.1e\n", ...
        rad2deg(cfgBase.meas.sigmaBearing),cfgBase.T,cfgBase.dt, ...
        cfgBase.ekf.q_acc);
    fprintf("burn: start=%.1f s, duration=%.1f s, a=%.3e m/s^2\n", ...
        cfgBase.control.obs.startTime,cfgBase.control.obs.burnDuration, ...
        cfgBase.control.obs.acceleration);

    for ic = 1:nCases
        cfg = cfgBase;
        cfg.control.obs.mode = maneuverModes(ic);
        cfg.control.obs.enabled = maneuverModes(ic) ~= "none";
        cfg.step.name = "step01_baseline_coast_" + maneuverModes(ic);
        configs{ic} = cfg;

        fprintf("\n%s (%s)...\n",caseNames(ic),maneuverModes(ic));
        try
            % Paired initial errors and paired standard-normal measurement
            % draws.  Only the noiseless bearing geometry changes.
            rng(seed);
            res = simulatePhysicalEKF(cfg);
            assert(all(isfinite(res.xhat(:))), ...
                "Non-finite physical estimate was produced.");
            results{ic} = res;
            status(ic) = "ok";
        catch ME
            status(ic) = "failed: " + string(ME.message);
            warning("%s failed: %s",caseNames(ic),ME.message);
        end
    end

    positionRMSE = NaN(nCases,1);
    finalPositionRMSE = NaN(nCases,1);
    exactRangeRMSE = NaN(nCases,1);
    finalExactRangeRMSE = NaN(nCases,1);
    crossTrackRMSE = NaN(nCases,1);
    velocityRMSE = NaN(nCases,1);
    finalVelocityRMSE = NaN(nCases,1);
    meanLOSProfileChangeSigma = NaN(nCases,1);
    maxLOSProfileChangeSigma = NaN(nCases,1);
    maxManeuverDisplacement = NaN(nCases,1);
    maxAdditionalThrust = NaN(nCases,1);

    perWatcherWhole = NaN(nCases,cfgBase.Nw);
    perWatcherFinal = NaN(nCases,cfgBase.Nw);
    initialTrueRange = NaN(nCases,cfgBase.Nw);

    if ~isempty(results{1})
        for ic = 1:nCases
            if isempty(results{ic})
                continue;
            end
            m = summarizeBaselineCase(results{ic},results{1},configs{ic});
            positionRMSE(ic) = m.positionRMSE;
            finalPositionRMSE(ic) = m.finalPositionRMSE;
            exactRangeRMSE(ic) = m.exactRangeRMSE;
            finalExactRangeRMSE(ic) = m.finalExactRangeRMSE;
            crossTrackRMSE(ic) = m.crossTrackRMSE;
            velocityRMSE(ic) = m.velocityRMSE;
            finalVelocityRMSE(ic) = m.finalVelocityRMSE;
            meanLOSProfileChangeSigma(ic) = m.meanLOSProfileChangeSigma;
            maxLOSProfileChangeSigma(ic) = m.maxLOSProfileChangeSigma;
            maxManeuverDisplacement(ic) = m.maxManeuverDisplacement;
            maxAdditionalThrust(ic) = m.maxAdditionalThrust;
            perWatcherWhole(ic,:) = m.perWatcherWhole;
            perWatcherFinal(ic,:) = m.perWatcherFinal;
            initialTrueRange(ic,:) = m.initialTrueRange;
        end
    end

    summary = table(caseNames,maneuverModes,status,positionRMSE, ...
        finalPositionRMSE,exactRangeRMSE,finalExactRangeRMSE, ...
        crossTrackRMSE,velocityRMSE,finalVelocityRMSE, ...
        meanLOSProfileChangeSigma,maxLOSProfileChangeSigma, ...
        maxManeuverDisplacement,maxAdditionalThrust, ...
        'VariableNames',{'caseName','maneuverMode','status', ...
        'positionRMSE','finalPositionRMSE','exactRangeRMSE', ...
        'finalExactRangeRMSE','crossTrackRMSE','velocityRMSE', ...
        'finalVelocityRMSE','meanLOSProfileChangeSigma', ...
        'maxLOSProfileChangeSigma','maxManeuverDisplacement', ...
        'maxAdditionalThrust'});
    disp(summary);

    caseColumn = repelem(caseNames,cfgBase.Nw,1);
    watcherColumn = repmat((1:cfgBase.Nw).',nCases,1);
    watcherRangeSummary = table(caseColumn,watcherColumn, ...
        reshape(initialTrueRange.',[],1),reshape(perWatcherWhole.',[],1), ...
        reshape(perWatcherFinal.',[],1), ...
        'VariableNames',{'caseName','watcher','initialTrueRange', ...
        'rangeRMSE','finalRangeRMSE'});
    disp(watcherRangeSummary);

    figures = gobjects(0);
    if makePlots && ~isempty(results{1})
        figures = plotBaselineAblation(results,summary, ...
            perWatcherWhole,perWatcherFinal,configs{1});
    end

    sweep = struct;
    sweep.summary = summary;
    sweep.watcherRangeSummary = watcherRangeSummary;
    sweep.results = results;
    sweep.configs = configs;
    sweep.seed = seed;
    sweep.figures = figures;
end

function m = summarizeBaselineCase(res,resReference,cfg)
    dim = cfg.dim;
    [~,N,Nw] = size(res.xhat);
    finalIdx = max(1,round(0.9*N)):N;

    etaTrue = repmat(reshape(res.etaTrue,2*dim,N,1),1,1,Nw);
    posError = res.xhat(1:dim,:,:) - etaTrue(1:dim,:,:);
    velIdx = dim+(1:dim);
    velError = res.xhat(velIdx,:,:) - etaTrue(velIdx,:,:);

    targetPosition = repmat( ...
        reshape(res.etaTrue(1:dim,:),dim,N,1),1,1,Nw);
    relativeTrue = targetPosition-res.watcherR;
    relativeHat = res.xhat(1:dim,:,:)-res.watcherR;
    rangeTrue = reshape(sqrt(sum(relativeTrue.^2,1)),N,Nw);
    rangeHat = reshape(sqrt(sum(relativeHat.^2,1)),N,Nw);
    rangeError = rangeHat-rangeTrue;
    losUnit = relativeTrue ./ max(reshape(rangeTrue,1,N,Nw),realmin);

    positionNorm = reshape(sqrt(sum(posError.^2,1)),N,Nw);
    losProjection = reshape(sum(posError.*losUnit,1),N,Nw);
    crossTrackNorm = sqrt(max(positionNorm.^2-losProjection.^2,0));
    velocityNorm = reshape(sqrt(sum(velError.^2,1)),N,Nw);

    relativeReference = targetPosition-resReference.watcherR;
    referenceLOS = relativeReference ./ ...
        max(sqrt(sum(relativeReference.^2,1)),realmin);
    losDot = reshape(sum(losUnit.*referenceLOS,1),N,Nw);
    losAngle = acos(max(-1,min(1,losDot)));
    losChangeSigma = losAngle/cfg.meas.sigmaBearing;

    deltaR = res.watcherR-resReference.watcherR;
    displacement = reshape(sqrt(sum(deltaR.^2,1)),N,Nw);
    deltaU = res.watcherU-resReference.watcherU;
    additionalThrust = reshape(sqrt(sum(deltaU.^2,1)),N,Nw);
    postManeuver = res.time >= cfg.control.obs.startTime;

    m.positionRMSE = rmsAll(positionNorm);
    m.finalPositionRMSE = rmsAll(positionNorm(finalIdx,:));
    m.exactRangeRMSE = rmsAll(rangeError);
    m.finalExactRangeRMSE = rmsAll(rangeError(finalIdx,:));
    m.crossTrackRMSE = rmsAll(crossTrackNorm);
    m.velocityRMSE = rmsAll(velocityNorm);
    m.finalVelocityRMSE = rmsAll(velocityNorm(finalIdx,:));
    m.meanLOSProfileChangeSigma = mean( ...
        losChangeSigma(postManeuver,:),"all","omitnan");
    m.maxLOSProfileChangeSigma = max(losChangeSigma(:));
    m.maxManeuverDisplacement = max(displacement(:));
    m.maxAdditionalThrust = max(additionalThrust(:));
    m.perWatcherWhole = sqrt(mean(rangeError.^2,1,"omitnan"));
    m.perWatcherFinal = sqrt(mean(rangeError(finalIdx,:).^2,1,"omitnan"));
    m.initialTrueRange = rangeTrue(1,:);
end

function figures = plotBaselineAblation(results,summary,wholeByWatcher, ...
        finalByWatcher,cfg)
    valid = summary.status == "ok";
    labels = summary.caseName(valid);
    colors = lines(height(summary));

    f1 = figure('Name','Step 01 baseline EKF maneuver summary');
    tiledlayout(2,2,'TileSpacing','compact');

    nexttile;
    bar(categorical(labels),[summary.exactRangeRMSE(valid), ...
        summary.finalExactRangeRMSE(valid)]);
    grid on; ylabel('range RMSE [m]');
    title('Known-dynamics angle-only range');
    legend('whole run','final 10%','Location','best');

    nexttile;
    bar(categorical(labels),[summary.positionRMSE(valid), ...
        summary.finalPositionRMSE(valid)]);
    grid on; ylabel('position RMSE [m]');
    title('Target position');
    legend('whole run','final 10%','Location','best');

    nexttile;
    bar(categorical(labels),[summary.meanLOSProfileChangeSigma(valid), ...
        summary.maxLOSProfileChangeSigma(valid)]);
    hold on; yline(3,'k:','3 sigma'); grid on;
    ylabel('bearing-profile change / sigma_b');
    title('Maneuver detectability');
    legend('post-burn mean','maximum','Location','best');

    nexttile;
    bar(categorical(labels),[summary.velocityRMSE(valid), ...
        summary.finalVelocityRMSE(valid)]);
    grid on; ylabel('velocity RMSE [m/s]');
    title('Target velocity');
    legend('whole run','final 10%','Location','best');

    f2 = figure('Name','Step 01 baseline EKF maneuver histories');
    tiledlayout(2,2,'TileSpacing','compact');
    for panel = 1:3
        nexttile; hold on; grid on;
        for ic = 1:numel(results)
            if isempty(results{ic}), continue; end
            plot(results{ic}.time,baselineTimeSeries(results{ic},panel), ...
                'LineWidth',1.05,'Color',colors(ic,:));
        end
        xline(cfg.control.obs.startTime,'k:','burn start');
        xline(cfg.control.obs.startTime+cfg.control.obs.burnDuration, ...
            'k--','burn end');
        xlabel('time [s]');
        if panel == 1
            title('Mean target position error'); ylabel('error [m]');
            legend(summary.caseName(valid),'Location','best');
        elseif panel == 2
            title('RMS exact-range error'); ylabel('error [m]');
        else
            title('Mean velocity error'); ylabel('error [m/s]');
        end
    end

    nexttile;
    bar(categorical(labels),[wholeByWatcher(valid,:),finalByWatcher(valid,:)]);
    grid on; ylabel('range RMSE [m]');
    title('Watcher-specific range performance');
    legend(["W1 whole","W2 whole","W3 whole","W4 whole", ...
        "W1 final","W2 final","W3 final","W4 final"], ...
        'Location','best');

    f3 = figure('Name','Step 01 baseline EKF watcher range histories');
    tiledlayout(2,2,'TileSpacing','compact');
    for iw = 1:cfg.Nw
        nexttile; hold on; grid on;
        for ic = 1:numel(results)
            if isempty(results{ic}), continue; end
            rangeError = exactRangeError(results{ic});
            plot(results{ic}.time,rangeError(:,iw), ...
                'LineWidth',0.9,'Color',colors(ic,:));
        end
        yline(0,'k:');
        xline(cfg.control.obs.startTime,'k:');
        xline(cfg.control.obs.startTime+cfg.control.obs.burnDuration,'k--');
        title(sprintf('Watcher %d exact-range error',iw));
        xlabel('time [s]'); ylabel('error [m]');
        if iw == 1
            legend(summary.caseName(valid),'Location','best');
        end
    end

    figures = [f1;f2;f3];
end

function series = baselineTimeSeries(res,panel)
    dim = size(res.etaTrue,1)/2;
    [~,N,Nw] = size(res.xhat);
    etaTrue = repmat(reshape(res.etaTrue,2*dim,N,1),1,1,Nw);
    if panel == 1
        e = res.xhat(1:dim,:,:)-etaTrue(1:dim,:,:);
        series = mean(reshape(sqrt(sum(e.^2,1)),N,Nw),2,"omitnan");
    elseif panel == 2
        e = exactRangeError(res);
        series = sqrt(mean(e.^2,2,"omitnan"));
    else
        idx = dim+(1:dim);
        e = res.xhat(idx,:,:)-etaTrue(idx,:,:);
        series = mean(reshape(sqrt(sum(e.^2,1)),N,Nw),2,"omitnan");
    end
end

function rangeError = exactRangeError(res)
    dim = size(res.etaTrue,1)/2;
    [~,N,Nw] = size(res.xhat);
    targetPosition = repmat( ...
        reshape(res.etaTrue(1:dim,:),dim,N,1),1,1,Nw);
    rangeTrue = reshape(sqrt(sum( ...
        (targetPosition-res.watcherR).^2,1)),N,Nw);
    rangeHat = reshape(sqrt(sum( ...
        (res.xhat(1:dim,:,:)-res.watcherR).^2,1)),N,Nw);
    rangeError = rangeHat-rangeTrue;
end

function value = rmsAll(x)
    value = sqrt(mean(x(:).^2,"omitnan"));
end
