addpath(genpath(pwd));
rehash;

out09f4 = run_step09f4_compare_additive_vs_gated_diagnostics( ...
    "complex_branchwise", 101, 0.5);

disp(out09f4.trackingSummary(:, [
    "gsCompositeMode", ...
    "localMeanPosErr_m", ...
    "gsMeanPosErr_m", ...
    "gsMeanImprovementPct", ...
    "gsRmsImprovementPct", ...
    "gsP95ImprovementPct"]));

disp(out09f4.residualOverallSummary(:, [
    "caseName", ...
    "compositeMode", ...
    "meanOperationalErr", ...
    "meanSameInputErr", ...
    "rmsOperationalErr", ...
    "rmsSameInputErr", ...
    "p95OperationalErr", ...
    "p95SameInputErr"]));