addpath(genpath(pwd));
rehash;

out09f9 = run_step09f9_compare_three_composite_modes_diagnostics( ...
    "complex_branchwise", 101, 0.5);

disp(out09f9.trackingSummary(:, [
    "gsCompositeMode", ...
    "gsMeanPosErr_m", ...
    "gsMeanImprovementPct", ...
    "gsRmsImprovementPct", ...
    "gsP95ImprovementPct"]));

disp(out09f9.residualOverallSummary(:, [
    "caseName", ...
    "compositeMode", ...
    "meanOperationalErr", ...
    "meanSameInputErr", ...
    "rmsOperationalErr", ...
    "rmsSameInputErr", ...
    "p95OperationalErr", ...
    "p95SameInputErr"]));