addpath(genpath(pwd));
rehash;

outAdd = run_step09c0_compare_always_available_Local_GS_Oracle( ...
    "complex_branchwise", 101, false, 0.5, [], "additive");

outGate = run_step09c0_compare_always_available_Local_GS_Oracle( ...
    "complex_branchwise", 101, false, 0.5, [], "gated_additive");

outHybrid = run_step09c0_compare_always_available_Local_GS_Oracle( ...
    "complex_branchwise", 101, false, 0.5, [], "local_full_plus_gated_nonlocal");

T = [
    outAdd.compactComparisonTable
    outGate.compactComparisonTable
    outHybrid.compactComparisonTable
    ];

disp(T(:, [
    "residualFamily", ...
    "seed", ...
    "gsCompositeMode", ...
    "localMeanPosErr_m", ...
    "gsMeanPosErr_m", ...
    "oracleMeanPosErr_m", ...
    "gsMeanImprovementPct", ...
    "gsRmsImprovementPct", ...
    "gsP95ImprovementPct", ...
    "localMeanNIS", ...
    "gsMeanNIS"]));