function report = check_step10C1_GS_impulse_replay(out)
%CHECK_STEP10C1_GS_IMPULSE_REPLAY Validate source maneuver and replay identity.

    required = ["source","trajectory","resLocal","resAdd", ...
        "resOutputInformation","summary"];
    assert(all(isfield(out,required)),"Step 10-C.1 output is incomplete.");
    source = out.source;
    trajectory = out.trajectory;
    replayResults = {out.resLocal,out.resAdd,out.resOutputInformation};
    assert(any(source.controllerActive(:)), ...
        "Source run did not execute an observability-triggered impulse.");
    assert(any(vecnorm(source.watcherU,2,1) > 0,"all"), ...
        "Source run logged no nonzero watcher force.");
    for i = 1:numel(replayResults)
        res = replayResults{i};
        assert(isequaln(res.etaTrue,trajectory.etaTrue), ...
            "Replay %d target truth differs from exported trajectory.",i);
        assert(isequaln(res.watcherR,trajectory.watcherR) && ...
            isequaln(res.watcherV,trajectory.watcherV), ...
            "Replay %d watcher trajectory differs from export.",i);
        if isfield(res,"controllerActive")
            assert(~any(res.controllerActive(:)), ...
                "Replay %d invoked a live controller.",i);
        end
    end
    assert(all(isfinite(out.summary.residualAtTrueEtaRMSE)), ...
        "Residual-at-true-state metrics must be finite.");
    report = struct("passed",true, ...
        "numSourceImpulseSteps",nnz(source.controllerActive), ...
        "finalImpulse",source.cumulativeImpulse(end,:), ...
        "finalDeltaV",source.cumulativeDeltaV(end,:));
    fprintf("Step 10-C.1 replay check passed: %d source impulse steps.\n", ...
        report.numSourceImpulseSteps);
end
