function aUnk = trueResidual(t, eta, cfg)
%{
Function:
    trueResidual.m

Purpose:
    Compute the unknown target acceleration residual used only in the truth
    dynamics.

    This function creates the model mismatch that the DNN-EKF will later try
    to learn.

    The true target dynamics are

        dot r_t = v_t,

        dot v_t = a_nom(r_t,v_t,t) + d_unk(eta,t).

    The physical EKF prediction model should not use this function.

Inputs:
    t      - Current simulation time [s].
    eta    - True target physical state, eta = [r_t; v_t].
             Size: 2*cfg.dim x 1.
    cfg    - Simulation configuration structure.

Outputs:
    aUnk   - Unknown target acceleration residual.
             Size: cfg.dim x 1.

Supported residual families:
    "smooth_synthetic"
        Simple smooth debugging residual.

    "simple_branchwise" or "branchwise"
        Current validated branchwise truth residual.

    "coupled_nonlinear"
        Smooth bounded residual with coupled position, velocity, swirl,
        radial, and localized nonlinear components.

    "feedback_sat_disturbance"
        Unknown feedback-control-like residual with smooth saturation,
        lateral maneuvering, state-dependent disturbance, and time-varying
        bias. This is intended as a more realistic hard benchmark.

Notes:
    - This function is used only by the truth model.
    - cfg.truth.residualFamily is the preferred new interface.
    - cfg.truth.residualModel is still supported for backward compatibility.
%}

    residualFamily = getResidualFamily_step09b1(cfg);

    switch residualFamily

        case "smooth_synthetic"
            aUnk = smoothSyntheticResidual(t, eta, cfg);

        case {"simple_branchwise", "branchwise"}
            aUnk = branchwiseResidual(eta, cfg);

        case "coupled_nonlinear"
            aUnk = coupledNonlinearResidual(t, eta, cfg);

        case "complex_branchwise"
            aUnk = complexBranchwiseResidual(t, eta, cfg);

        case "feedback_sat_disturbance"
            aUnk = feedbackSatDisturbanceResidual(t, eta, cfg);

        otherwise
            error("trueResidual:UnknownResidualFamily", ...
                "Unknown residual family/model: %s", residualFamily);

    end

end

function residualFamily = getResidualFamily_step09b1(cfg)
%GETRESIDUALFAMILY_STEP09B1 Resolve residual-family config.
%
% Preferred new field:
%     cfg.truth.residualFamily
%
% Backward-compatible old field:
%     cfg.truth.residualModel

    residualFamily = "smooth_synthetic";

    if isfield(cfg, "truth")

        if isfield(cfg.truth, "residualFamily")
            residualFamily = string(cfg.truth.residualFamily);

        elseif isfield(cfg.truth, "residualModel")
            residualFamily = string(cfg.truth.residualModel);
        end

    end

    % Normalize old naming to the new naming convention.
    if residualFamily == "branchwise"
        residualFamily = "simple_branchwise";
    end

end

function aUnk = smoothSyntheticResidual(t, eta, cfg)
%SMOOTHSYNTHETICRESIDUAL Compute a simple smooth synthetic unknown residual.
%
% This residual is mainly for debugging. It does not explicitly use the
% branch-wise DNN structure.

    dim = cfg.dim;

    r = eta(1:dim);

    if isfield(cfg, "truth") && isfield(cfg.truth, "residualAmp")
        A = cfg.truth.residualAmp;
    else
        A = 1e-4;
    end

    if dim == 2
        x = r(1);
        y = r(2);

        aUnk = A * [ ...
            sin(0.01*x + 0.001*t);
            cos(0.01*y - 0.001*t) ];

    elseif dim == 3
        x = r(1);
        y = r(2);
        z = r(3);

        aUnk = A * [ ...
            sin(0.01*x + 0.001*t);
            cos(0.01*y - 0.001*t);
            sin(0.01*z + 0.002*t) ];

    else
        error("trueResidual:UnsupportedDimension", ...
            "Unsupported cfg.dim. Use cfg.dim = 2 or cfg.dim = 3.");
    end

end

function aUnk = branchwiseResidual(eta, cfg)
%BRANCHWISERESIDUAL Compute hidden branch-wise truth residual.
%
% Main equation:
%     d_unk(eta) = sum_j W_j^star phi_j(eta)
%
% The hidden weights W_j^star are generated by truthBranchWeights.m.
% This uses the same branch structure as the current fixed-feature DNN-EKF
% model, but the EKF does not know theta_j^star.

    [branchTruth, ~] = truthBranchWeights(cfg);

    [aUnk, ~] = compositeResidual(eta, branchTruth, cfg);

end

function aUnk = coupledNonlinearResidual(t, eta, cfg)
%COUPLEDNONLINEARRESIDUAL Smooth coupled nonlinear truth residual.
%
% Purpose:
%     Provide a harder benchmark than the current simple branchwise residual.
%
% Structure:
%     a_unk = A * (
%           radial nonlinear component
%         + swirl / transverse component
%         + velocity-coupled component
%         + localized operating-region bump
%         + weak time variation
%     )
%
% Design goals:
%     - Smooth and bounded.
%     - Coupled in position and velocity.
%     - More difficult for one local fixed-feature branch to approximate.
%     - Still numerically safe for EKF simulation.

    dim = cfg.dim;

    if numel(eta) < 2*dim
        error("trueResidual:BadEtaSize", ...
            "eta must have at least 2*cfg.dim entries.");
    end

    r = eta(1:dim);
    v = eta(dim+1:2*dim);

    A = getTruthScalar_step09b3(cfg, "residualAmp", 5e-4);

    % Normalization scales keep the synthetic functions well-conditioned.
    rScale = getTruthScalar_step09b3(cfg, "coupledResidualPositionScale", 1000.0);
    vScale = getTruthScalar_step09b3(cfg, "coupledResidualVelocityScale", 0.1);
    tScale = getTruthScalar_step09b3(cfg, "coupledResidualTimeScale", 1200.0);

    x = r / max(rScale, eps);
    u = v / max(vScale, eps);
    tau = t / max(tScale, eps);

    if dim == 2
        aUnk = coupledNonlinearResidual2D_step09b3(x, u, tau, A);

    elseif dim == 3
        aUnk = coupledNonlinearResidual3D_step09b3(x, u, tau, A);

    else
        error("trueResidual:UnsupportedDimension", ...
            "coupled_nonlinear supports cfg.dim = 2 or cfg.dim = 3.");
    end

end

function aUnk = coupledNonlinearResidual2D_step09b3(x, u, tau, A)
%COUPLEDNONLINEARRESIDUAL2D_STEP09B3 2-D coupled nonlinear residual.

    tiny = 1e-12;

    x1 = x(1);
    x2 = x(2);

    u1 = u(1);
    u2 = u(2);

    rho = norm(x);

    if rho > tiny
        eRad = x / rho;
    else
        eRad = [1.0; 0.0];
    end

    % Transverse direction creates a smooth swirl-like residual component.
    eTan = [-eRad(2); eRad(1)];

    radialMag = 0.45 * sin(1.7*x1 - 1.1*x2 + 0.35*u2 + 0.25*sin(tau));
    swirlMag  = 0.65 * tanh(1.2*x1 + 0.8*x2 + 0.50*u1 - 0.20*cos(tau));

    % Velocity-coupled term makes the residual depend on both r and v.
    velCoupled = 0.25 * [ ...
        sin(u1 + 0.7*x2 + 0.15*cos(tau));
        cos(u2 - 0.6*x1 + 0.15*sin(tau)) ];

    % Localized bump makes the residual region-dependent.
    center = [0.35; -0.25];
    bumpWidth = 0.18;
    bump = exp(-sum((x - center).^2) / bumpWidth);

    bumpVec = 0.35 * bump * [1.0; -0.6];

    rawResidual = ...
        radialMag * eRad + ...
        swirlMag  * eTan + ...
        velCoupled + ...
        bumpVec;

    % tanh bounds each component while preserving smoothness.
    aUnk = A * tanh(rawResidual);

end

function aUnk = coupledNonlinearResidual3D_step09b3(x, u, tau, A)
%COUPLEDNONLINEARRESIDUAL3D_STEP09B3 3-D coupled nonlinear residual.

    tiny = 1e-12;

    x1 = x(1);
    x2 = x(2);
    x3 = x(3);

    u1 = u(1);
    u2 = u(2);
    u3 = u(3);

    rho = norm(x);

    if rho > tiny
        eRad = x / rho;
    else
        eRad = [1.0; 0.0; 0.0];
    end

    % Fixed inertial axis used only to define a smooth transverse direction.
    axis = [0.35; -0.20; 1.0];
    axis = axis / norm(axis);

    eSwirl = cross(axis, eRad);

    if norm(eSwirl) < tiny
        eSwirl = [0.0; 1.0; 0.0];
    else
        eSwirl = eSwirl / norm(eSwirl);
    end

    eCross = cross(eRad, eSwirl);
    eCross = eCross / max(norm(eCross), tiny);

    radialMag = 0.45 * sin(1.5*x1 - 1.0*x2 + 0.6*x3 + 0.30*u2 + 0.20*sin(tau));
    swirlMag  = 0.65 * tanh(1.1*x1 + 0.7*x2 - 0.5*x3 + 0.45*u1 - 0.20*cos(tau));
    crossMag  = 0.30 * sin(0.8*x1 + 1.3*x3 + 0.25*u3 + 0.15*sin(2*tau));

    velCoupled = 0.22 * [ ...
        sin(u1 + 0.6*x2 + 0.10*cos(tau));
        cos(u2 - 0.5*x1 + 0.10*sin(tau));
        sin(u3 + 0.4*x1 - 0.3*x2) ];

    center = [0.35; -0.25; 0.15];
    bumpWidth = 0.22;
    bump = exp(-sum((x - center).^2) / bumpWidth);

    bumpVec = 0.35 * bump * [1.0; -0.6; 0.4];

    rawResidual = ...
        radialMag * eRad + ...
        swirlMag  * eSwirl + ...
        crossMag  * eCross + ...
        velCoupled + ...
        bumpVec;

    % tanh bounds each component while preserving smoothness.
    aUnk = A * tanh(rawResidual);

end

function value = getTruthScalar_step09b3(cfg, fieldName, defaultValue)
%GETTRUTHSCALAR_STEP09B3 Read scalar cfg.truth field with a default.

    value = defaultValue;

    if isfield(cfg, "truth") && isfield(cfg.truth, fieldName)
        candidate = cfg.truth.(fieldName);

        if ~isempty(candidate) && isscalar(candidate) && isfinite(candidate)
            value = candidate;
        end
    end

end


function aUnk = complexBranchwiseResidual(t, eta, cfg)
%COMPLEXBRANCHWISERESIDUAL Branch-consistent complex residual truth model.
%
% Purpose:
%     Provide a harder residual benchmark that is still consistent with the
%     GS-assisted branch-sharing architecture.
%
% Main structure:
%     d_true(eta,t) = sum_j d_j^star(eta,t)
%
% where each d_j^star is a smooth bounded nonlinear branch contribution.
%
% Difference from simple_branchwise:
%     simple_branchwise is exactly generated by the same fixed-feature
%     output-layer model used by the estimator.
%
%     complex_branchwise is still branch-additive, but each branch contains
%     nonlinear coupled terms that are not exactly represented by the
%     current fixed-feature branch model.
%
% Difference from coupled_nonlinear:
%     coupled_nonlinear is a global residual with no explicit branch
%     decomposition.
%
%     complex_branchwise has an explicit branch decomposition, so it is a
%     cleaner benchmark for Local-vs-GS branch sharing.

    dim = cfg.dim;
    Nw = cfg.Nw;

    if numel(eta) < 2*dim
        error("trueResidual:BadEtaSize", ...
            "eta must have at least 2*cfg.dim entries.");
    end

    r = eta(1:dim);
    v = eta(dim+1:2*dim);

    A = getTruthScalar_step09b3(cfg, "residualAmp", 5e-4);

    % Normalization scales. Keep these separate from the DNN feature scales
    % so the truth model can be adjusted without changing estimator code.
    rScale = getTruthScalar_step09b3(cfg, ...
        "complexBranchwisePositionScale", 1000.0);

    vScale = getTruthScalar_step09b3(cfg, ...
        "complexBranchwiseVelocityScale", 0.1);

    tScale = getTruthScalar_step09b3(cfg, ...
        "complexBranchwiseTimeScale", 1200.0);

    x = r / max(rScale, eps);
    u = v / max(vScale, eps);
    tau = t / max(tScale, eps);

    aUnk = zeros(dim, 1);

    for j = 1:Nw

        if dim == 2
            branchComponent = complexBranchwiseComponent2D_step09d1( ...
                j, Nw, x, u, tau);

        elseif dim == 3
            branchComponent = complexBranchwiseComponent3D_step09d1( ...
                j, Nw, x, u, tau);

        else
            error("trueResidual:UnsupportedDimension", ...
                "complex_branchwise supports cfg.dim = 2 or cfg.dim = 3.");
        end

        % Scale each branch so the total residual remains residualAmp-order.
        aUnk = aUnk + (A / max(Nw, 1)) * branchComponent;

    end

    % Final componentwise bounding for numerical safety.
    aUnk = A * tanh(aUnk / max(A, eps));

end

function branchComponent = complexBranchwiseComponent2D_step09d1(j, Nw, x, u, tau)
%COMPLEXBRANCHWISECOMPONENT2D_STEP09D1 2-D branch contribution.

    psi = 2*pi*(j-1)/Nw;

    e1 = [cos(psi); sin(psi)];
    e2 = [-sin(psi); cos(psi)];

    x1 = e1' * x;
    x2 = e2' * x;

    u1 = e1' * u;
    u2 = e2' * u;

    % Smooth branch-local gate. It changes branch activity by operating
    % region but remains positive, so branches do not disappear completely.
    gate = 0.65 + 0.35*tanh(1.3*x1 - 0.4*x2 + 0.25*sin(tau + psi));

    % Directional nonlinear terms.
    mag1 = 0.85 * sin(1.4*x1 + 0.55*u2 + 0.25*sin(tau + psi));
    mag2 = 0.55 * tanh(-0.8*x2 + 0.45*u1 + 0.20*cos(0.7*tau + psi));

    % Weak coupled term that cannot be captured perfectly by the current
    % fixed-feature output-layer branch.
    coupled = 0.25 * [ ...
        sin(0.7*x1*x2 + 0.20*u1 + 0.15*cos(tau));
        cos(0.5*x1 - 0.6*u2 + 0.15*sin(tau + psi)) ];

    % Localized branch bump with branch-dependent center.
    center = 0.35 * [cos(psi + 0.4); sin(psi + 0.4)];
    bumpWidth = 0.25;
    bump = exp(-sum((x - center).^2) / bumpWidth);

    bumpVec = 0.30 * bump * (0.8*e1 - 0.4*e2);

    raw = gate * (mag1*e1 + mag2*e2) + coupled + bumpVec;

    branchComponent = tanh(raw);

end

function branchComponent = complexBranchwiseComponent3D_step09d1(j, Nw, x, u, tau)
%COMPLEXBRANCHWISECOMPONENT3D_STEP09D1 3-D branch contribution.

    psi = 2*pi*(j-1)/Nw;

    e1 = [cos(psi); sin(psi); 0.35*sin(0.5*psi + 0.2)];
    e1 = e1 / max(norm(e1), eps);

    ref = [0.0; 0.0; 1.0];

    if abs(e1' * ref) > 0.95
        ref = [0.0; 1.0; 0.0];
    end

    e2 = cross(ref, e1);
    e2 = e2 / max(norm(e2), eps);

    e3 = cross(e1, e2);
    e3 = e3 / max(norm(e3), eps);

    x1 = e1' * x;
    x2 = e2' * x;
    x3 = e3' * x;

    u1 = e1' * u;
    u2 = e2' * u;
    u3 = e3' * u;

    gate = 0.65 + 0.35*tanh(1.1*x1 - 0.5*x2 + 0.3*x3 + 0.25*sin(tau + psi));

    mag1 = 0.80 * sin(1.3*x1 + 0.40*x3 + 0.50*u2 + 0.20*sin(tau + psi));
    mag2 = 0.55 * tanh(-0.7*x2 + 0.35*u1 - 0.20*u3 + 0.15*cos(0.8*tau + psi));
    mag3 = 0.35 * sin(0.9*x3 + 0.25*u3 + 0.25*x1*x2 + 0.10*sin(1.5*tau));

    coupled = 0.20 * [ ...
        sin(0.6*x1*x2 + 0.20*u1);
        cos(0.5*x2 - 0.4*u2 + 0.15*sin(tau + psi));
        sin(0.4*x1 + 0.5*x3 + 0.20*u3) ];

    center = 0.35 * [ ...
        cos(psi + 0.4);
        sin(psi + 0.4);
        0.4*sin(psi - 0.2) ];

    bumpWidth = 0.30;
    bump = exp(-sum((x - center).^2) / bumpWidth);

    bumpVec = 0.28 * bump * (0.7*e1 - 0.3*e2 + 0.2*e3);

    raw = gate * (mag1*e1 + mag2*e2 + mag3*e3) + coupled + bumpVec;

    branchComponent = tanh(raw);

end


function aUnk = feedbackSatDisturbanceResidual(t, eta, cfg)
%FEEDBACKSATDISTURBANCERESIDUAL Feedback-control + saturation + disturbance.
%
% Purpose:
%     Provide a more realistic truth residual than the previous synthetic
%     fields. This residual behaves as if the target has an unknown internal
%     feedback controller, smooth actuator saturation, lateral maneuvering,
%     state-dependent disturbance, and slowly varying bias.
%
% Truth model interpretation:
%     dot r = v
%     dot v = a_nom(r,v,t) + d_true(r,v,t)
%
%     d_true is unknown to the EKF/DNN-EKF and is generated here only for the
%     truth simulation.
%
% Main structure:
%     d_true =
%         sat_aMax(
%             feedback control
%           + lateral/swirl maneuver
%           + periodic disturbance
%           + state-dependent disturbance
%           + slowly varying bias
%         )
%
% Important:
%     The final tanh saturation keeps the residual bounded and smooth. This
%     avoids hard clipping, which would introduce nonsmooth behavior.

    dim = cfg.dim;

    if numel(eta) < 2*dim
        error("trueResidual:BadEtaSize", ...
            "eta must have at least 2*cfg.dim entries.");
    end

    r = eta(1:dim);
    v = eta(dim+1:2*dim);

    % ---------------------------------------------------------------------
    % Main magnitude and normalization scales
    % ---------------------------------------------------------------------
    % residualAmp remains the main top-level knob so existing runners can
    % change residual difficulty without needing a new config interface.
    A = getTruthScalar_step09b3(cfg, "residualAmp", 5e-4);

    rScale = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualPositionScale", 1000.0);

    vScale = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualVelocityScale", 0.1);

    tScale = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualTimeScale", 1200.0);

    x = r / max(rScale, eps);
    u = v / max(vScale, eps);
    tau = t / max(tScale, eps);

    % Final componentwise saturation level. By default this is residualAmp.
    aMax = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualSaturation", A);

    % ---------------------------------------------------------------------
    % Moving reference for unknown feedback control
    % ---------------------------------------------------------------------
    % This makes the target-side controller time-varying. The estimator does
    % not know this reference.
    refAmp = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualRefAmp", 0.25);

    refOmega = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualRefOmega", 0.85);

    if dim == 2
        xRef = refAmp * [ ...
            cos(refOmega*tau + 0.30);
            sin(refOmega*tau + 0.30) ];

        uRef = refAmp * refOmega * [ ...
            -sin(refOmega*tau + 0.30);
             cos(refOmega*tau + 0.30) ];

    elseif dim == 3
        xRef = refAmp * [ ...
            cos(refOmega*tau + 0.30);
            sin(refOmega*tau + 0.30);
            0.35*sin(0.55*refOmega*tau + 0.80) ];

        uRef = refAmp * [ ...
            -refOmega*sin(refOmega*tau + 0.30);
             refOmega*cos(refOmega*tau + 0.30);
             0.35*0.55*refOmega*cos(0.55*refOmega*tau + 0.80) ];

    else
        error("trueResidual:UnsupportedDimension", ...
            "feedback_sat_disturbance supports cfg.dim = 2 or cfg.dim = 3.");
    end

    eX = x - xRef;
    eU = u - uRef;

    % ---------------------------------------------------------------------
    % Unknown target feedback-control-like term
    % ---------------------------------------------------------------------
    Kp = getTruthScalar_step09b3(cfg, "feedbackResidualKp", 0.80);
    Kd = getTruthScalar_step09b3(cfg, "feedbackResidualKd", 0.35);

    Knl = getTruthScalar_step09b3(cfg, "feedbackResidualKnl", 0.35);
    Kvnl = getTruthScalar_step09b3(cfg, "feedbackResidualKvnl", 0.18);

    uFeedback = ...
        -Kp * eX ...
        -Kd * eU ...
        -Knl * tanh(1.6 * eX) ...
        -Kvnl * tanh(1.2 * eU);

    % ---------------------------------------------------------------------
    % Lateral/swirl maneuver
    % ---------------------------------------------------------------------
    % This term makes the unknown control more than a simple stabilizing PD
    % residual. In 2-D it creates transverse acceleration. In 3-D it creates
    % a smooth swirl direction using a fixed reference axis.
    swirlGain = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualSwirlGain", 0.55);

    tiny = 1e-12;
    rho = norm(eX);

    if dim == 2

        if rho > tiny
            eRad = eX / rho;
        else
            eRad = [1.0; 0.0];
        end

        eTan = [-eRad(2); eRad(1)];

        swirlGate = tanh(2.0 * rho + 0.25*sin(tau));

        uSwirl = swirlGain * swirlGate * eTan;

    else

        if rho > tiny
            eRad = eX / rho;
        else
            eRad = [1.0; 0.0; 0.0];
        end

        axis = [0.25; -0.15; 1.0];
        axis = axis / norm(axis);

        eSwirl = cross(axis, eRad);

        if norm(eSwirl) < tiny
            eSwirl = [0.0; 1.0; 0.0];
        else
            eSwirl = eSwirl / norm(eSwirl);
        end

        swirlGate = tanh(2.0 * rho + 0.25*sin(tau));

        uSwirl = swirlGain * swirlGate * eSwirl;

    end

    % ---------------------------------------------------------------------
    % Periodic disturbance
    % ---------------------------------------------------------------------
    % Smooth deterministic disturbances represent unmodeled target actuation,
    % environmental mismatch, or flexible-mode-like effects.
    periodicGain = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualPeriodicGain", 0.30);

    dPeriodic = zeros(dim, 1);

    if dim >= 1
        dPeriodic(1) = periodicGain * ...
            sin(1.7*tau + 0.8*x(1) - 0.4*u(1));
    end

    if dim >= 2
        dPeriodic(2) = periodicGain * ...
            cos(1.1*tau - 0.7*x(2) + 0.5*u(2));
    end

    if dim == 3
        dPeriodic(3) = 0.7*periodicGain * ...
            sin(1.3*tau + 0.5*x(3) + 0.3*u(3));
    end

    % ---------------------------------------------------------------------
    % State-dependent disturbance
    % ---------------------------------------------------------------------
    % This part is deliberately not identical to the current fixed-feature
    % LIP estimator. It contains tanh nonlinearities, cross-products, and
    % coupled trigonometric terms.
    stateGain = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualStateGain", 0.45);

    if dim == 2

        x1 = x(1);
        x2 = x(2);
        u1 = u(1);
        u2 = u(2);

        dState = stateGain * [ ...
            0.60*tanh(1.3*x1 - 0.7*u2) ...
          + 0.30*sin(0.9*x1*x2 + 0.5*u1) ...
          + 0.20*tanh(1.2*(x1*u1 + x2*u2));

            0.55*tanh(-1.1*x2 + 0.6*u1) ...
          + 0.25*cos(0.8*x1 - 0.9*u2) ...
          - 0.20*tanh(1.0*(x1*u2 - x2*u1)) ];

    else

        x1 = x(1);
        x2 = x(2);
        x3 = x(3);
        u1 = u(1);
        u2 = u(2);
        u3 = u(3);

        dState = stateGain * [ ...
            0.55*tanh(1.2*x1 - 0.6*u2) ...
          + 0.25*sin(0.7*x1*x2 + 0.4*u1);

            0.50*tanh(-1.0*x2 + 0.5*u1) ...
          + 0.25*cos(0.6*x1 - 0.8*u2);

            0.45*tanh(0.9*x3 + 0.4*u3) ...
          + 0.20*sin(0.5*x1*x3 - 0.3*x2*u3) ];
    end

    % ---------------------------------------------------------------------
    % Slowly varying bias
    % ---------------------------------------------------------------------
    biasGain = getTruthScalar_step09b3(cfg, ...
        "feedbackResidualBiasGain", 0.18);

    if dim == 2
        dBias = biasGain * [ ...
            tanh(sin(0.45*tau + 0.3));
            tanh(cos(0.35*tau + 1.1)) ];
    else
        dBias = biasGain * [ ...
            tanh(sin(0.45*tau + 0.3));
            tanh(cos(0.35*tau + 1.1));
            tanh(sin(0.25*tau - 0.6)) ];
    end

    % ---------------------------------------------------------------------
    % Combine and saturate
    % ---------------------------------------------------------------------
    raw = ...
        uFeedback ...
      + uSwirl ...
      + dPeriodic ...
      + dState ...
      + dBias;

    % Scale by A and then apply final smooth acceleration saturation.
    aRaw = A * raw;

    aUnk = aMax * tanh(aRaw / max(aMax, eps));

end