function summary = summarizeStep10A2Replay(res,cfg,caseName)
%SUMMARIZESTEP10A2REPLAY Compact metric set for fixed-trajectory replays.
    dim = cfg.dim;
    [~,N,Nw] = size(res.xhat);
    finalIdx = max(1,round(0.9*N)):N;
    etaTrue = repmat(reshape(res.etaTrue,2*dim,N,1),1,1,Nw);
    posErr = vecnorm(res.xhat(1:dim,:,:)-etaTrue(1:dim,:,:),2,1);
    velIdx = dim+(1:dim);
    velErr = vecnorm(res.xhat(velIdx,:,:)-etaTrue(velIdx,:,:),2,1);
    posErr = reshape(posErr,N,Nw);
    velErr = reshape(velErr,N,Nw);
    rTrue = repmat(reshape(res.etaTrue(1:dim,:),dim,N,1),1,1,Nw);
    rangeErr = vecnorm(res.xhat(1:dim,:,:)-res.watcherR,2,1) - ...
        vecnorm(rTrue-res.watcherR,2,1);
    rangeErr = reshape(rangeErr,N,Nw);
    dTrue = repmat(reshape(res.trueResidual,dim,N,1),1,1,Nw);
    dErr = vecnorm(res.dnnResidual-dTrue,2,1);
    dErr = reshape(dErr,N,Nw);

    summary = table(string(caseName), ...
        sqrt(mean(posErr(:).^2,"omitnan")), ...
        sqrt(mean(posErr(finalIdx,:).^2,"all","omitnan")), ...
        sqrt(mean(rangeErr(:).^2,"omitnan")), ...
        sqrt(mean(rangeErr(finalIdx,:).^2,"all","omitnan")), ...
        sqrt(mean(velErr(:).^2,"omitnan")), ...
        sqrt(mean(velErr(finalIdx,:).^2,"all","omitnan")), ...
        sqrt(mean(dErr(:).^2,"omitnan")), ...
        sqrt(mean(dErr(finalIdx,:).^2,"all","omitnan")), ...
        'VariableNames',{'caseName','positionRMSE','finalPositionRMSE', ...
        'rangeRMSE','finalRangeRMSE','velocityRMSE', ...
        'finalVelocityRMSE','residualVectorRMSE', ...
        'finalResidualVectorRMSE'});
end
